// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlQdtULCIM1SvoFdYfdXWWjH6o0b4u_OQ',
    appId: '1:770477538820:web:311bcf6ae4125b7c9c7f51',
    messagingSenderId: '770477538820',
    projectId: 'aisos-flutter-project',
    authDomain: 'aisos-flutter-project.firebaseapp.com',
    storageBucket: 'aisos-flutter-project.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD5jcRHAYp6GLZaAMFvGUL_TEWBO4LrhiQ',
    appId: '1:770477538820:android:076fcedcfdd454a29c7f51',
    messagingSenderId: '770477538820',
    projectId: 'aisos-flutter-project',
    storageBucket: 'aisos-flutter-project.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA5iojbntmXVN2bIO4oJ4vcFv3FlZvisXo',
    appId: '1:770477538820:ios:059b6403a96ac9169c7f51',
    messagingSenderId: '770477538820',
    projectId: 'aisos-flutter-project',
    storageBucket: 'aisos-flutter-project.appspot.com',
    iosClientId: '770477538820-esdjsi30aip9k0h174h4tvl1nj9d2kpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisosApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA5iojbntmXVN2bIO4oJ4vcFv3FlZvisXo',
    appId: '1:770477538820:ios:059b6403a96ac9169c7f51',
    messagingSenderId: '770477538820',
    projectId: 'aisos-flutter-project',
    storageBucket: 'aisos-flutter-project.appspot.com',
    iosClientId: '770477538820-esdjsi30aip9k0h174h4tvl1nj9d2kpe.apps.googleusercontent.com',
    iosBundleId: 'com.example.aisosApp',
  );
}
